version: "3.5"
name: score_service

include:
  - broker/docker-compose.yml

services:
  score_api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - score_net
    depends_on:
      score_postgres:
        condition: service_healthy
    env_file:
      - .env

  score_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - score_net
    depends_on:
      - score_api
    ports:
      - "8081:81"

  score_postgres:
    image: postgres:16
    env_file: .env
    networks:
      - score_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  consumer:
    build:
      context: .
      dockerfile: worker/Dockerfile
    networks:
      - score_net
    env_file:
      - .env
    environment:
      - DB_ADDRESS=192.168.3.99
      - TZ=Europe/Moscow
    restart: unless-stopped

networks:
  score_net:
    name: score_net